# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hcremers <hcremers@student.s19.be>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/01/18 13:44:00 by hcremers          #+#    #+#              #
#    Updated: 2023/02/05 18:35:00 by hcremers         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    healthcheck:
      interval: 30s
      retries: 5
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-u",
          "$MARIADB_USER",
          "-p$MARIADB_PWD"
        ]
      timeout: 30s
    image: mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mariadb-volume:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    image: wordpress
    networks:
      - inception
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - wordpress-volume:/var/www/wordpress

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    image: nginx
    networks:
      - inception
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      - wordpress-volume:/var/www/wordpress

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/hcremers/data/database
      o: bind
      type: volume

  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/hcremers/data/wordpress
      o: bind
      type: volume

networks:
  inception:
