# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hcremers <hcremers@student.s19.be>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/01/18 13:44:00 by hcremers          #+#    #+#              #
#    Updated: 2023/01/18 13:44:50 by hcremers         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb
    # If you really want to use MySQL, uncomment the following line
    # image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - /home/hcremers/data
    restart: always
    # environment:
    #   - MYSQL_ROOT_PASSWORD=somewordpress
    #   - MYSQL_DATABASE=wordpress
    #   - MYSQL_USER=wordpress
    #   - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060

  wordpress:
    image: wordpress
    volumes:
      - /home/hcremers/data
    ports:
      - 80:80
    restart: always
    # environment:
    #   - WORDPRESS_DB_HOST=db
    #   - WORDPRESS_DB_USER=wordpress
    #   - WORDPRESS_DB_PASSWORD=wordpress
    #   - WORDPRESS_DB_NAME=wordpress

volumes:
  db_data:
  wp_data:
