version: "3.7"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    image: mariadb
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - mariadb-volume:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    image: wordpress
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - wordpress-volume:/var/www/wordpress

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    image: nginx
    networks:
      - inception
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      - wordpress-volume:/var/www/wordpress

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/hcremers/data/database
      o: bind
      type: volume

  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/hcremers/data/wordpress
      o: bind
      type: volume

networks:
  inception:
